version: "3"

services:
  # api:
  #   build: ./api
  #   ports:
  #     - $API_PORT:$CONTAINER_PORT
  #   depends_on:
  #     - postgres

  front:
    container_name: front
    build:
      context: ./front
      args:
        WORKDIR: $WORKDIR
        FRONT_PORT: $FRONT_PORT
        CONTAINER_PORT: $CONTAINER_PORT
    volumes:
      - ./front:/$WORKDIR
    ports:
      - $FRONT_PORT:$CONTAINER_PORT
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    # depends_on:
    #   - api
#   postgres:
#     image: postgres
#     volumes:
#       - "db-data:/var/lib/postgresql/data"
#     environment:
#       - "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
#       - "POSTGRES_USER=$POSTGRES_USER"
# volumes:
#   db-data:
